"""Serialise an entry to the on-disk `.entry.yaml` form.

Field order is fixed and matches the hand-written entries. That is not fussiness:
these files are reviewed by people in a PR diff, and a stable order is what makes
a one-line change to a confidence value show up as a one-line change.
"""
from __future__ import annotations

import os
from typing import Any

import yaml

FIELD_ORDER = [
    "id", "instance_of", "lemma", "domain", "domain_sense", "status", "contributed_by",
    "grounding", "causal", "ethics", "svo", "glyph_block", "metaphor_type",
    "provenance", "term_findings",
]

HEADER = """\
# GENERATED BY nsjepa_contrib {version} — DO NOT HAND-EDIT IN PLACE.
# Regenerate from the deployment, or promote to a hand-maintained entry by
# moving it out of contrib/ and deleting this header.
#
# Contributed by {vendor} ({product}), deployment {deployment}.
# Interstate category {category}{docket}.
#
# status: provisional. A contributor cannot ratify its own entry. Only ratified
# entries may feed institution-level aggregation — the gate exists because once
# instances aggregate to NAMED institutions, evidence tier stops being a nicety
# and becomes a defamation surface.
"""


class _Dumper(yaml.SafeDumper):
    pass


def _str_presenter(dumper, data):
    if "\n" in data or len(data) > 88:
        return dumper.represent_scalar("tag:yaml.org,2002:str", data, style=">")
    return dumper.represent_scalar("tag:yaml.org,2002:str", data)


_Dumper.add_representer(str, _str_presenter)


def _prune(obj: Any) -> Any:
    """Drop None and empty containers, EXCEPT an empty warrants list, which is
    the escalation signal and must survive to the file."""
    if isinstance(obj, dict):
        out = {}
        for k, v in obj.items():
            if k == "warrants":
                out[k] = v
                continue
            pv = _prune(v)
            if pv is None or pv == [] or pv == {} or pv == "":
                continue
            out[k] = pv
        return out
    if isinstance(obj, list):
        return [_prune(v) for v in obj]
    return obj


def to_yaml(entry: dict, version: str = "0.1.0") -> str:
    cb = entry.get("contributed_by", {})
    header = HEADER.format(
        version=version,
        vendor=cb.get("vendor_id", "?"),
        product=cb.get("product", "?"),
        deployment=cb.get("deployment_id", "?"),
        category=cb.get("category", "?"),
        docket=f", docket {cb['docket_reference']}" if cb.get("docket_reference") else "",
    )
    pruned = _prune(entry)
    ordered = {k: pruned[k] for k in FIELD_ORDER if k in pruned}
    ordered.update({k: v for k, v in pruned.items() if k not in FIELD_ORDER})
    body = yaml.dump(ordered, Dumper=_Dumper, sort_keys=False,
                     default_flow_style=False, width=88, allow_unicode=True)
    return header + body


def contrib_path(entry: dict, root: str = ".") -> str:
    """Where a contributed entry lands.

    `contrib/<vendor>/<deployment>/<lemma>.entry.yaml`, deliberately OUTSIDE
    `domains/<domain>/entries/`. Vendor-submitted data stays out of the
    canonical namespace until a maintainer promotes it, which makes the
    ratification gate structural rather than a field anyone could flip.
    """
    cb = entry["contributed_by"]
    lemma_slug = entry["id"].split(":", 1)[1].split("#", 1)[0]
    return os.path.join(root, "contrib", cb["vendor_id"], cb["deployment_id"],
                        lemma_slug + ".entry.yaml")


def write(entry: dict, root: str = ".", version: str = "0.1.0") -> str:
    path = contrib_path(entry, root)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(to_yaml(entry, version))
    return path
